name: affirmative_sentence
description: "A Flutter application for positive affirmations"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^14.0.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  provider: ^6.1.1
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/translations/
    - data/phrases.json
    - lib/l10n/
